"""SQLAlchemy ORM model for the JobSummary entity."""

from datetime import datetime
from typing import Any

from sqlalchemy import (
    DateTime,
    Float,
    ForeignKey,
    JSON,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class JobSummary(Base):
    __tablename__ = "job_summaries"

    # ── Primary key ───────────────────────────────────────────────
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # ── Foreign key (one-to-one with Job) ─────────────────────────
    job_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
        comment="Parent job UUID (unique — one summary per job)",
    )

    # ── Aggregate spend ───────────────────────────────────────────
    total_spend_inr: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Total amount spent in INR across all transactions",
    )
    total_spend_usd: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Total amount spent in USD across all transactions",
    )

    # ── JSON columns ──────────────────────────────────────────────
    # top_merchants: [{"merchant": "Amazon", "total": 45000.00}, ...]
    top_merchants: Mapped[list[dict[str, Any]] | None] = mapped_column(
        JSON,
        nullable=True,
        comment="Top 3 merchants by spend volume as a JSON list",
    )

    # category_breakdown: {"Shopping": 45000.00, "Food": 12000.00, ...}
    category_breakdown: Mapped[dict[str, float] | None] = mapped_column(
        JSON,
        nullable=True,
        comment="Spend per category as a JSON object",
    )

    # ── Summary fields ────────────────────────────────────────────
    anomaly_count: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        comment="Total number of flagged anomalies for this job",
    )
    narrative: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="2–3 sentence spending narrative generated by the LLM",
    )
    risk_level: Mapped[str | None] = mapped_column(
        String(10),
        nullable=True,
        comment="low | medium | high — assessed by the LLM",
    )

    # ── Audit ─────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    # ── Relationship ──────────────────────────────────────────────
    job: Mapped["Job"] = relationship("Job", back_populates="summary")  # noqa: F821

    def __repr__(self) -> str:
        return (
            f"<JobSummary job_id={self.job_id!r} risk_level={self.risk_level!r}>"
        )
